# Generated by Django 5.2.7 on 2025-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit amount (if applicable)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='lock_in_period',
            field=models.PositiveIntegerField(blank=True, help_text='Lock-in period in months (if applicable)', null=True),
        ),
    ]
