# Generated by Django 5.2.7 on 2025-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_age_user_contact_number_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='pg_type',
            field=models.CharField(choices=[('boys', 'Only Boys'), ('girls', 'Only Girls'), ('coed', 'Co-ed')], default='coed', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
