# Generated by Django 5.2.7 on 2025-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_gender_pg_pg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pg_images/'),
        ),
    ]
